[package]
name = "heartbeats-simple"
version = "0.1.0"
authors = ["Connor Imes <connor.k.imes@gmail.com>"]
description = "Rust wrappers for heartbeats-simple-sys"
license = "MIT"
homepage = "https://github.com/connorimes/heartbeats-simple-rust"
repository = "https://github.com/connorimes/heartbeats-simple-rust"
keywords = ["heartbeats", "timing", "accuracy", "performance", "energy", "power"]

[dependencies]
libc = "0.1"

[dependencies.hbs-pow-sys]
git = "https://github.com/connorimes/heartbeats-simple-sys.git"
